// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfqpixipfnaspvdnjbrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcXBpeGlwZm5hc3B2ZG5qYnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDM2NjYsImV4cCI6MjA1NTIxOTY2Nn0.0z9tQjN0L-fnGx-zxIP2hknOWXia-Wb7bmEoDI8fTcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);